<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\editor\Entity\Editor;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function test_d8_help($route_name, RouteMatchInterface $route_match){
  switch ($route_name) {
    case 'help.page.test_d8':
      $output = '';
      $output .= '<h3>'.t('About').'</h3>';
      $output .= '<p>'.t('Please send help').'</p>';

      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function test_d8_theme($existing, $type, $theme, $path){
  return [
    'chart_tests_drupal8' => [
      'template' => 'chart-tests-drupal8',
      'variables' => ['data' => NULL]
    ],
    'timer_qcm_test_drupal8' => [
      'template' => 'timer-qcm-test-drupal8',
      'variables' => ['data' => NULL]
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 */
function test_d8_page_attachments(array &$page){
  $routeName = \Drupal::routeMatch()->getRouteName();
  //kint($routeName);die();
  if ($routeName == 'test_drupal8.qcm') {
    $page['#attached']['library'][] = 'test_d8/library-qcm-test-drupal8';
  }
  elseif ($routeName == 'view.tests_drupal_8.page_1') {
    $page['#attached']['library'][] = 'test_d8/library-view-list-tests-drupal8';
  }
  elseif ($routeName == 'view.tests_drupal_8.page_2') {
    $page['#attached']['library'][] = 'test_d8/library-view-instructions-tests-drupal8';
  }
  elseif ($routeName == 'entity.user.canonical' ) {
    $page['#attached']['library'][] = 'test_d8/library-user-dashboard-tests-drupal8';
  }
}

/**
 * Implements template_preprocess_html().
 */
// send settings to JS
function test_d8_preprocess_html(&$variables) {
  $settings = \Drupal::config('test_d8.settings');
  $time_to_complete_test = $settings->get('time_to_complete_test');
  $number_of_questions = $settings->get('number_of_questions');

  $variables['#attached']['drupalSettings']['TestD8']['time_to_complete_test'] = $time_to_complete_test;
  $variables['#attached']['drupalSettings']['TestD8']['number_of_questions'] = $number_of_questions;
}

/**
 * Implements hook_form_alter().
 */
function test_d8_form_alter(&$form, FormStateInterface $form_state, $form_id){
  if ($form_id == 'views_ui_config_item_form' && !empty($form['options']['content'])) {
    $form['options']['content']['#editor'] = TRUE;
  }
  /*if ($form_id == 'testd8_form') {
    kint($form);
    kint($form_state);
    exit;
  }*/
}

/*
function test_d8_preprocess_page(&$variables){
  kint($variables);
  exit;
}
*/

